"""Record and/or enforce quarantine of detected flaky tests.

Dual-mode, controlled by the ``quarantine.mode`` config flag
("report" | "apply" | "both"):

- ``write_known_flakes``: merges findings into memory/known_flakes.md,
  preserving history. Never overwrites prior entries.
- ``apply_quarantine_marks``: writes conftest/marker config into the
  target repo so flagged tests are skipped/xfailed.
"""

from __future__ import annotations

import json
import os
import re
import tempfile
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any

from flake_hunter.models import FlakeReport

_LEDGER_TITLE = "# Known Flakes"
_TABLE_HEADER = "| Test ID | First Seen | Pass Count | Fail Count | Suspected Cause | Status |"
_TABLE_DIVIDER = "| --- | --- | --- | --- | --- | --- |"

_XFAIL_FAIL_RATE_THRESHOLD = 0.5
_QUARANTINE_MARKS_RELATIVE_PATH = Path(".flake_hunter") / "quarantine_marks.json"

_CONFTEST_HOOK_MARKER = "pytest_collection_modifyitems"
_CONFTEST_SENTINEL = "# --- flake-hunter quarantine marks ---"
_CONFTEST_SNIPPET = f"""
{_CONFTEST_SENTINEL}
# Auto-generated by flake_hunter.quarantine.apply_quarantine_marks.
# Reruns update .flake_hunter/quarantine_marks.json in place; this
# block itself is written once and never duplicated.
from pathlib import Path

import pytest

from flake_hunter.quarantine import load_marks


def pytest_collection_modifyitems(items: list[pytest.Item]) -> None:
    marks = load_marks(Path(__file__).parent)
    for item in items:
        mark = marks.get(item.nodeid)
        if mark == "skip":
            item.add_marker(pytest.mark.skip(reason="flake-hunter: quarantined as flaky"))
        elif mark == "xfail":
            item.add_marker(pytest.mark.xfail(reason="flake-hunter: quarantined as flaky"))
"""


# Matches "|" not preceded by a backslash, so an escaped pipe inside a
# cell (e.g. a parametrized nodeid like test_thing[a\|b]) isn't mistaken
# for a table column separator.
_ROW_SPLIT_RE = re.compile(r"(?<!\\)\|")


def _escape_pipes(text: str) -> str:
    return text.replace("|", "\\|")


def _unescape_pipes(text: str) -> str:
    return text.replace("\\|", "|")


def _safe_int(value: str) -> int:
    try:
        return int(value)
    except ValueError:
        return 0


def _atomic_write_text(path: Path, content: str) -> None:
    """Write ``content`` to ``path`` without ever leaving a truncated file.

    Writes to a temp file in the same directory then ``os.replace()``s it
    into place, so a crash mid-write can't corrupt the target. This is
    about crash resilience for a single invocation, not mutual exclusion
    between concurrent flake-hunter runs -- see plan.md for why that's
    out of scope.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as tmp_file:
            tmp_file.write(content)
        if path.exists():
            os.chmod(tmp_name, path.stat().st_mode)
        else:
            umask = os.umask(0)
            os.umask(umask)
            os.chmod(tmp_name, 0o666 & ~umask)
        os.replace(tmp_name, path)
    except BaseException:
        Path(tmp_name).unlink(missing_ok=True)
        raise


@dataclass(slots=True)
class _LedgerRow:
    nodeid: str
    first_seen: str
    pass_count: int
    fail_count: int
    suspected_cause: str
    status: str


def _parse_ledger(known_flakes_path: Path) -> dict[str, _LedgerRow]:
    if not known_flakes_path.exists():
        return {}

    rows: dict[str, _LedgerRow] = {}
    for line in known_flakes_path.read_text().splitlines():
        stripped = line.strip()
        if not stripped.startswith("|") or not stripped.endswith("|"):
            continue
        cells = [_unescape_pipes(cell.strip()) for cell in _ROW_SPLIT_RE.split(stripped)[1:-1]]
        if len(cells) != 6 or cells[0] in ("Test ID", "---"):
            continue
        nodeid, first_seen, pass_count, fail_count, suspected_cause, status = cells
        rows[nodeid] = _LedgerRow(
            nodeid=nodeid,
            first_seen=first_seen,
            pass_count=_safe_int(pass_count),
            fail_count=_safe_int(fail_count),
            suspected_cause=suspected_cause,
            status=status,
        )
    return rows


def write_known_flakes(reports: list[FlakeReport], known_flakes_path: Path) -> None:
    """Merge newly detected flakes into the known_flakes.md ledger.

    Existing rows are matched by nodeid and updated in place (counts
    refreshed, ``first_seen``/``suspected_cause`` preserved); nodeids new
    to this batch are appended with today's date and an "unknown" cause
    placeholder (no failure-classifier exists yet). Rows for nodeids
    absent from this batch -- tests no longer observed as flaky -- are
    never dropped, so history is never lost.
    """
    rows = _parse_ledger(known_flakes_path)
    today = date.today().isoformat()

    for report in reports:
        existing = rows.get(report.nodeid)
        rows[report.nodeid] = _LedgerRow(
            nodeid=report.nodeid,
            first_seen=existing.first_seen if existing else today,
            pass_count=report.pass_count,
            fail_count=report.fail_count + report.error_count,
            suspected_cause=existing.suspected_cause if existing else "unknown",
            status="flaky",
        )

    lines = [_LEDGER_TITLE, "", _TABLE_HEADER, _TABLE_DIVIDER]
    for row in sorted(rows.values(), key=lambda row: row.nodeid):
        lines.append(
            f"| {_escape_pipes(row.nodeid)} | {row.first_seen} | {row.pass_count} | "
            f"{row.fail_count} | {row.suspected_cause} | {row.status} |"
        )

    _atomic_write_text(known_flakes_path, "\n".join(lines) + "\n")


def apply_quarantine_marks(reports: list[FlakeReport], target_repo_path: Path) -> None:
    """Write conftest/marker config to skip/xfail flagged tests in the target repo.

    Tests failing at least half the time (``fail_rate >=
    _XFAIL_FAIL_RATE_THRESHOLD``) are marked ``xfail`` (expected to fail
    more often than not); the rest are marked ``skip``. The marks JSON
    file is fully rewritten every call -- it holds only the current
    batch's findings, not history (unlike ``write_known_flakes``).
    """
    marks = {
        report.nodeid: ("xfail" if report.fail_rate >= _XFAIL_FAIL_RATE_THRESHOLD else "skip")
        for report in reports
    }

    marks_path = target_repo_path / _QUARANTINE_MARKS_RELATIVE_PATH
    _atomic_write_text(marks_path, json.dumps(marks, indent=2, sort_keys=True) + "\n")

    conftest_path = target_repo_path / "conftest.py"
    existing = conftest_path.read_text() if conftest_path.exists() else ""
    if _CONFTEST_SENTINEL in existing and _CONFTEST_HOOK_MARKER in existing:
        return

    separator = "" if not existing or existing.endswith("\n") else "\n"
    _atomic_write_text(conftest_path, existing + separator + _CONFTEST_SNIPPET)


def load_marks(target_repo_path: Path) -> dict[str, str]:
    """Read the nodeid -> "skip"|"xfail" marks written by apply_quarantine_marks.

    Degrades to ``{}`` on a missing or malformed marks file, mirroring
    parser.parse_run's degrade-gracefully pattern -- never raises.
    """
    marks_path = target_repo_path / _QUARANTINE_MARKS_RELATIVE_PATH
    try:
        raw: Any = json.loads(marks_path.read_text())
    except (OSError, json.JSONDecodeError):
        return {}

    if not isinstance(raw, dict):
        return {}
    return {k: v for k, v in raw.items() if isinstance(k, str) and isinstance(v, str)}
